#!/bin/bash
#cmake -DLLVM_ENABLE_PROJECTS="clang;compiler-rt" -DCMAKE_BUILD_TYPE=Debug -DLLVM_TARGETS_TO_BUILD=Sodium -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_CCACHE_BUILD=On -DCMAKE_LINKER_TYPE=MOLD ..
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_PROJECTS="clang;lld" -DLLVM_TARGETS_TO_BUILD=Sodium -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_CCACHE_BUILD=On -DCMAKE_LINKER_TYPE=MOLD ..
